# Generated by Django 2.0.3 on 2018-04-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180412_0953'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(blank=True, to='account.User', verbose_name='作者'),
        ),
    ]
