# Generated by Django 2.0.3 on 2018-04-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180412_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
    ]
