# Generated by Django 2.0.3 on 2018-04-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180412_0953'),
        ('blog', '0005_remove_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='作者'),
        ),
    ]
