# Generated by Django 2.0.3 on 2018-04-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
    ]
