# Generated by Django 2.0.3 on 2018-04-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180412_1724'),
        ('blog', '0007_remove_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='用户'),
        ),
    ]
