# Generated by Django 2.0.4 on 2018-04-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180412_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
